// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    '❌ CRITICAL: Supabase credentials missing!\n' +
    'Please ensure .env file exists with:\n' +
    '- VITE_SUPABASE_URL\n' +
    '- VITE_SUPABASE_PUBLISHABLE_KEY\n\n' +
    'Copy .env.example to .env and add your credentials.'
  );
}

// Validate URL format
try {
  new URL(SUPABASE_URL);
} catch {
  throw new Error(
    `❌ CRITICAL: Invalid SUPABASE_URL format: ${SUPABASE_URL}\n` +
    'URL must be a valid HTTPS URL (e.g., https://xxx.supabase.co)'
  );
}

// Validate key format (basic check)
if (SUPABASE_PUBLISHABLE_KEY.length < 20) {
  throw new Error(
    '❌ CRITICAL: SUPABASE_PUBLISHABLE_KEY appears invalid (too short)\n' +
    'Please check your .env file'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});